version: "3"
services:
    cantaloupe:
        build: .
        container_name: ${PROJECT_NAME}_cantaloupe
        image: swissartresearx/cantaloupe:5.0
        restart: always
        volumes:
            - ./config:/config
            - ./assets:/assets
    jobs:
        build: ./services/jobs
        container_name: ${PROJECT_NAME}_jobs
        restart: unless-stopped
        volumes:
            - ./data:/data
            - ./scripts:/scripts
            - ./assets:/assets
        environment:
            - JAVA_OPTS=-Xms512m -Xmx1024m
            - COMPOSE_PROJECT_NAME=${PROJECT_NAME}
            - LOGIN=${LOGIN}
            - PASSWORD=${PASSWORD}