version: "3"
services:
    cantaloupe:
        build: .
        container_name: ${PROJECT_NAME}_cantaloupe
        image: swissartresearx/cantaloupe:5.0
        restart: always
        volumes:
            - ./config:/config
            - ./images:/images