version: "3"
services:
cantaloupe:
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${HOST_NAME}
      VIRTUAL_HOST: ${HOST_NAME}
      VIRTUAL_PORT: 8182
    networks:
    - proxy

networks:
  internal:
  proxy:
    external:
      name: nginx_proxy_network
